# Generated by Django 5.0.4 on 2024-04-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(default='0000', max_length=200)),
                ('is_leader', models.BooleanField(default=False)),
                ('hearts', models.IntegerField(default=0)),
            ],
        ),
    ]
